# commandline args generated by doc!
const doc = """
Sample Program.

Usage:
  opts parse [--debug] <filename>...
  opts (-h | --help)
  opts (-v | --version)

Options:
  -h --help     Show this screen.
  -v --version  Show version.
  --debug       Show useful information while parsing.
"""

import tables, strutils, docopt

let args = docopt(doc, version = "Sample Program 3.14")

if args["parse"]:
  echo "Parsing file $#".format(args["<filename>"])
  echo repr(args["<filename>"])