import "../mylist.nim", tables, future, strutils

block:
    ## Solution with CountTable
    var counts: CountTable[char] = initCountTable[char](4)

    for c in "ATAAATCCGGATACTTTTGGTAACTTATCTCTTAAATTCTGTAGGAATGACCTCACGCTATTGAAGCGGGAGATAGACTGACATCAAAATATAGTTAATATCTAGAATTCCCTTTCATCTGGGAACCCTTTTAAACCCGCACGCCGTGCAGAGTAACGCGCGGTCCTACCTTAGACGTTCGGAGTGTACCGATACCCAAGATTGGATACTGGGTGGTAAGTATCCCCAAATGCACCCCTGGAGACTCTCCAGCGAACTCCCAATGCCTTTCATGTCGAACGCTGTGGTGTTCTGTCATTTTGAGAACCCACAATTGTACGCGCGGCGGTTGTTGGCGCATCCACGGAGCACCCTCGTAACTGCCGGCCAAGAGGCATGGCATCGGGCCTGGGTCACTGCGGCGAAATTTCAGGAAGGCCACGGGTGGGATTTCTTTATGGTTTAATATCCCATTGTGCTCCAAAGCAGCTGCTTAGGCGTGCAACACGCTCCCAGCTTGTTACCGTGGTTTAAAGGAAGGAGTAGATACTAGGCAGAACGAACCCGGGGCAGCTTCCTCCGTCTTAAGATCTCATATATTGAGGCCTCCCATCCCCGAGTGCCGGCTCCACATTATTATGAACCTTTGAGTTCCAGTACACCCGACAAGTACCCTAGATCGAGTTCTGGACGAGATGTTCATGCTTCTCGCCTATGCCCATCTGAAGCACCACCAGTCCCCCAATCAGATTATAGGGACCCTAGGGCCGTCGTCTTGCGATACTACTCACTTTCGGACCCTCTTCCAGTAATCCCTCGCGAATAGCGCAACTTGTTCCGGTGCAACCTTAGCAGAGAACGCCATATTACGGATGGTAGCGTGGCCTGGTGGCGATC":
        if not counts.hasKey(c):
            counts[c] = 1
        else:
            counts[c] = counts[c] + 1

    echo($(counts['A']) & " " & $(counts['C']) & " " & $(counts['G']) & " " & $(counts['T'])) 


block:
    ## Solution with my lists and foldLeft
    const input = "ATAAATCCGGATACTTTTGGTAACTTATCTCTTAAATTCTGTAGGAATGACCTCACGCTATTGAAGCGGGAGATAGACTGACATCAAAATATAGTTAATATCTAGAATTCCCTTTCATCTGGGAACCCTTTTAAACCCGCACGCCGTGCAGAGTAACGCGCGGTCCTACCTTAGACGTTCGGAGTGTACCGATACCCAAGATTGGATACTGGGTGGTAAGTATCCCCAAATGCACCCCTGGAGACTCTCCAGCGAACTCCCAATGCCTTTCATGTCGAACGCTGTGGTGTTCTGTCATTTTGAGAACCCACAATTGTACGCGCGGCGGTTGTTGGCGCATCCACGGAGCACCCTCGTAACTGCCGGCCAAGAGGCATGGCATCGGGCCTGGGTCACTGCGGCGAAATTTCAGGAAGGCCACGGGTGGGATTTCTTTATGGTTTAATATCCCATTGTGCTCCAAAGCAGCTGCTTAGGCGTGCAACACGCTCCCAGCTTGTTACCGTGGTTTAAAGGAAGGAGTAGATACTAGGCAGAACGAACCCGGGGCAGCTTCCTCCGTCTTAAGATCTCATATATTGAGGCCTCCCATCCCCGAGTGCCGGCTCCACATTATTATGAACCTTTGAGTTCCAGTACACCCGACAAGTACCCTAGATCGAGTTCTGGACGAGATGTTCATGCTTCTCGCCTATGCCCATCTGAAGCACCACCAGTCCCCCAATCAGATTATAGGGACCCTAGGGCCGTCGTCTTGCGATACTACTCACTTTCGGACCCTCTTCCAGTAATCCCTCGCGAATAGCGCAACTTGTTCCGGTGCAACCTTAGCAGAGAACGCCATATTACGGATGGTAGCGTGGCCTGGTGGCGATC"

    let letters = listFromString(input)

    proc incMatching(n: int, cGiven, cExpected: char): int {.inline.} = 
        if cGiven == cExpected:
            return n + 1
        else:
            return n

    proc countLetter(x: char): (n: int, c: char) -> int =
        return (n: int, c: char) => incMatching(n, c, x)

    echo($(letters.foldLeft(0, countLetter('A'))) & " " & $(letters.foldLeft(0, countLetter('C'))) & " " & $(letters.foldLeft(0, countLetter('G'))) & " " & $(letters.foldLeft(0, countLetter('T'))))

block:
    ## Should be the fastest, since it's bound to the C function 'nsuCountChar'
    const input: string = "ATAAATCCGGATACTTTTGGTAACTTATCTCTTAAATTCTGTAGGAATGACCTCACGCTATTGAAGCGGGAGATAGACTGACATCAAAATATAGTTAATATCTAGAATTCCCTTTCATCTGGGAACCCTTTTAAACCCGCACGCCGTGCAGAGTAACGCGCGGTCCTACCTTAGACGTTCGGAGTGTACCGATACCCAAGATTGGATACTGGGTGGTAAGTATCCCCAAATGCACCCCTGGAGACTCTCCAGCGAACTCCCAATGCCTTTCATGTCGAACGCTGTGGTGTTCTGTCATTTTGAGAACCCACAATTGTACGCGCGGCGGTTGTTGGCGCATCCACGGAGCACCCTCGTAACTGCCGGCCAAGAGGCATGGCATCGGGCCTGGGTCACTGCGGCGAAATTTCAGGAAGGCCACGGGTGGGATTTCTTTATGGTTTAATATCCCATTGTGCTCCAAAGCAGCTGCTTAGGCGTGCAACACGCTCCCAGCTTGTTACCGTGGTTTAAAGGAAGGAGTAGATACTAGGCAGAACGAACCCGGGGCAGCTTCCTCCGTCTTAAGATCTCATATATTGAGGCCTCCCATCCCCGAGTGCCGGCTCCACATTATTATGAACCTTTGAGTTCCAGTACACCCGACAAGTACCCTAGATCGAGTTCTGGACGAGATGTTCATGCTTCTCGCCTATGCCCATCTGAAGCACCACCAGTCCCCCAATCAGATTATAGGGACCCTAGGGCCGTCGTCTTGCGATACTACTCACTTTCGGACCCTCTTCCAGTAATCCCTCGCGAATAGCGCAACTTGTTCCGGTGCAACCTTAGCAGAGAACGCCATATTACGGATGGTAGCGTGGCCTGGTGGCGATC"
    
    echo($(input.count('A')) & " " & $(input.count('C')) & " " & $(input.count('G')) & " " & $(input.count('T')))